name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use Node.js 20, compatible with Next.js 15
          cache: 'npm' # Cache npm dependencies

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run linting
      - name: Run lint
        run: npm run lint

      # Run TypeScript type checking
      - name: Run type check
        run: npx tsc --noEmit

      # Run tests
      - name: Run tests
        run: npm test
        env:
          CI: true

      # Build the Next.js application
      - name: Build application
        run: npm run build

      # Optional: Add deployment steps here (e.g., to Vercel)
      # - name: Deploy to Vercel
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: npx vercel --prod
      #   env:
      #     VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
