name: CI Pipeline for Next.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Sesuaikan dengan versi Node.js yang digunakan proyek Anda

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      - name: Run tests (if available)
        run: npm test || echo "No tests defined"
